version: "3.9"

services:
  ace-of-spades-api:
    build: .
    container_name: ace-of-spades-api-container
    ports:
      - "17071:17071"
    volumes:
      - .:/app
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:11.1.4
    container_name: maria-db-ace-container
    env_file: "./.env"
    ports:
      - "3306:3306"
    volumes:
      - ./initialize.sql:/docker-entrypoint-initdb.d/initialize.sql
    logging:
      driver: "none"
